# Generated by Django 5.1.7 on 2025-03-21 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inclusao', models.DateTimeField(auto_now_add=True)),
                ('ambiente', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('tempo_espera', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('satisfacao', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('atendimento', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('sugestoes', models.TextField(blank=True, null=True)),
                ('incluir_contato', models.BooleanField(default=False)),
                ('contato_nome', models.CharField(blank=True, help_text='Opcional', max_length=255, null=True)),
                ('contato_telefoe', models.CharField(blank=True, help_text='Opcional', max_length=20, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='servicos.local_de_atendimento')),
            ],
        ),
    ]
