# Generated by Django 5.1.7 on 2025-05-30 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_pesquisasatisfacao'),
        ('servicos', '0004_local_de_atendimento_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='servicos.local_de_atendimento'),
        ),
    ]
