# Generated by Django 5.1.7 on 2025-05-30 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_alter_pesquisasatisfacao_local'),
        ('servicos', '0004_local_de_atendimento_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='servicos.local_de_atendimento'),
        ),
    ]
