# Generated by Django 5.1.7 on 2025-05-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_alter_pesquisasatisfacao_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='impressora_item5_porque',
            field=models.CharField(blank=True, help_text="Se 'Não', explique o motivo", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='internet_item3_porque',
            field=models.CharField(blank=True, help_text="Se 'Não', explique o motivo", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='sistema_gestao_item2_porque',
            field=models.CharField(blank=True, help_text="Se 'Não', explique o motivo", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='sistema_gestao_item3porque',
            field=models.CharField(blank=True, help_text="Se 'Não', explique o motivo", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='suporte_item4_porque',
            field=models.CharField(blank=True, help_text="Se 'Não', explique o motivo", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='telefonia_item2_porque',
            field=models.CharField(blank=True, help_text="Se 'Não', explique o motivo", max_length=255, null=True),
        ),
    ]
