# Generated by Django 5.1.7 on 2025-06-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_pesquisasatisfacao_impressora_item5_porque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='impressora_item6',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='internet_item5',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='sistema_gestao_item1',
            field=models.CharField(choices=[('pro', 'Protocolo'), ('gma', 'GMA'), ('tri', 'Tributário'), ('out', 'Outro'), ('n/a', 'Não se aplica')], default='n/a', max_length=3),
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='suporte_item42',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='telefonia_item6',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='suporte_item4',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, verbose_name='Telefonia Item 4'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='suporte_item4_porque',
            field=models.CharField(blank=True, help_text="Se 'Não', explique o motivo", max_length=255, null=True, verbose_name='Telefonia Item 4'),
        ),
    ]
