# Generated by Django 5.1.7 on 2025-06-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0006_pesquisasatisfacao_impressora_item6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='impressora_item6',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='internet_item5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='suporte_item42',
            field=models.IntegerField(blank=True, null=True, verbose_name='Suporte Item 4'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='suporte_item4_porque',
            field=models.CharField(blank=True, help_text="Se 'Não', explique o motivo", max_length=255, null=True, verbose_name='Telefonia Item 4 pq'),
        ),
        migrations.AlterField(
            model_name='pesquisasatisfacao',
            name='telefonia_item6',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
