# Generated by Django 5.1.7 on 2025-06-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0007_alter_pesquisasatisfacao_impressora_item6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='secretaria',
            field=models.CharField(blank=True, max_length=250, verbose_name='Secretaria'),
        ),
    ]
