# Generated by Django 5.1.7 on 2025-06-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0008_pesquisasatisfacao_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisasatisfacao',
            name='processo_item4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
