# Generated by Django 5.1.7 on 2025-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('idade', models.IntegerField()),
                ('escolaridade', models.CharField(max_length=255)),
                ('ocupacao', models.CharField(max_length=255)),
                ('rendimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portador_deficiencia', models.BooleanField()),
                ('tipos_deficiencia', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionarioSeharf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=255)),
                ('distrito', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('moradia_propria', models.BooleanField()),
                ('titulo_propriedade', models.BooleanField(blank=True, null=True)),
                ('possui_escritura', models.BooleanField(blank=True, null=True)),
                ('outros_imoveis', models.IntegerField(blank=True, null=True)),
                ('alugada', models.BooleanField(blank=True, null=True)),
                ('terreno_construcao_alugada', models.BooleanField(blank=True, null=True)),
                ('cedida', models.BooleanField(blank=True, null=True)),
                ('terreno_construcao_cedida', models.BooleanField(blank=True, null=True)),
                ('moradia_compartilhada', models.BooleanField(blank=True, null=True)),
                ('estado_conservacao', models.CharField(max_length=50)),
                ('tipo_construcao', models.CharField(max_length=50)),
                ('num_quartos', models.IntegerField()),
                ('num_banheiros', models.IntegerField()),
                ('seguranca', models.JSONField(blank=True, null=True)),
                ('tempo_deslocamento', models.CharField(max_length=50)),
                ('rua_pavimentacao', models.BooleanField()),
                ('bairro_transporte_publico', models.BooleanField()),
                ('rua_agua_tratada', models.BooleanField()),
                ('rua_rede_esgoto', models.BooleanField()),
                ('fossa_septica', models.BooleanField(blank=True, null=True)),
                ('rua_rede_pluvial', models.BooleanField()),
                ('bairro_area_lazer', models.BooleanField()),
                ('bairro_escola', models.BooleanField()),
                ('rua_rede_eletrica', models.BooleanField()),
                ('rua_internet', models.BooleanField()),
                ('bairro_creche', models.BooleanField()),
                ('pavimentacao', models.CharField(max_length=50)),
                ('gosta_bairro', models.BooleanField()),
                ('onde_gostaria_morar', models.TextField(blank=True, null=True)),
                ('melhor_bairro', models.TextField(blank=True, null=True)),
                ('sonho', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membros_familia', models.ManyToManyField(related_name='questionario_seharf', to='pesquisas.familymember')),
            ],
        ),
    ]
