# Generated by Django 4.2.20 on 2025-05-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionarioseharf',
            old_name='rua_rede_pluvial',
            new_name='rua_tem_rede_pluvial',
        ),
    ]
