# Generated by Django 5.1.7 on 2025-03-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_de_atendimento',
            name='hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
