# Generated by Django 5.1.7 on 2025-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_local_de_atendimento_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_de_atendimento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
