# Generated by Django 5.1.7 on 2025-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_local_de_atendimento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='local_de_atendimento',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
