# Generated by Django 4.2.20 on 2025-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botwhatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoatendimento',
            name='detalhamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaoatendimento',
            name='nome',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
